"""added a new column

Revision ID: 7340cdeefda7
Revises: 80915ce34334
Create Date: 2021-08-12 09:00:58.600701

"""

# revision identifiers, used by Alembic.
revision = '7340cdeefda7'
down_revision = '80915ce34334'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
