"""added a new column

Revision ID: 80915ce34334
Revises: acb7a786b2c4
Create Date: 2021-08-12 08:15:16.808443

"""

# revision identifiers, used by Alembic.
revision = '80915ce34334'
down_revision = 'acb7a786b2c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
