"""added a new column

Revision ID: acb7a786b2c4
Revises: 68c33683e65e
Create Date: 2021-08-11 15:08:30.896182

"""

# revision identifiers, used by Alembic.
revision = 'acb7a786b2c4'
down_revision = '68c33683e65e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
